#!/bin/sh

## hyphop ##

. ./,config

[ -f $src/._PREPARED_ ] && {
    echo "[i] prepared already!!!

NEXT:
    ./kernel_build_all
" 1>&2;

    exit 0
}


[ -d logs ] || mkdir logs

[ -s $src/Makefile ] || {

    #toolchain-arm_cortex-a9.neon_gcc-5.3.0_musl-1.1.15_eabi.squashfs

    [ -s $squash_src ] || {
	wget $squash_src_link -O ../$squash_src_name
    }

    [ -s $squash_src ] && {
	echo "mount squash & overlay"
	./mount_overlay_squash
    }
}


[ -s $src/Makefile ] || {
    [ -s $pack_src ] && {
	echo "unpack $pack_src"
	tar -xf $pack_src
    }
}

[ -s $src/Makefile ] || { 
    echo "get source from git"
    #git clone --depth 1 -b v2017.01 https://github.com/RobertCNelson/u-boot $src
    #rm -rd $src/.git
}

arm-openwrt-linux-gcc --version 2>/dev/null 1>/dev/null || {

    [ -s ../$tc_gcc_squash ] && {
	cmd="mount -o ro ../$tc_gcc_squash ../$tc_gcc_dir"
	echo $cmd
	$cmd
    }

#    [ -s $tc_gcc.tar.bz2 ] ||  wget $tc_src
#    tar -xf $tc_gcc.tar.bz2
#    ln -s $tc_gcc/$tc_gcc_dir $tc_gcc_dir
}

cd $bdir
#exit;
#ls -l1 $patches/

cd $src
cat ../$patches/*.patch | patch -p1
cp -a ../$add/* .
cd ..


./kernel_defconfig && {
    echo 1 > $src/._PREPARED_
    echo "[i] ok source is prepared

NEXT:
    ./kernel_build_all
" 1>&2

}

