#!/usr/bin/perl

## hyphop ##

our $PWD = $ENV{PWD};

our $kernel_out    = "bin";
our $mod_out       = "bin/modules.all";
our $mod_out_links = "bin/modules.links";

our ( $modname, $rmod, $mod );

open MODULES, ">$kernel_out/modules.list";
open MODNAME, ">$kernel_out/modnames.list";

our @MODULES;
our @MODNAMES;

while (<STDIN>) {

    chomp;
    $modname = $rmod = $mod = $_;
    $rmod    =~ s{$PWD/}{};
    $modname =~ s{.+/}{};

#    warn "$rmod => $mod_out/$modname";

    my $l1 = "$mod_out/$modname";
    my $l2 = "$mod_out_links/$modname";

    warn $l1 if -f $l1;
    warn $l2 if -f $l2;

    my $npath = $rmod;
    $npath =~ s{^$kernel_out/}{};

    push @MODULES, $npath;
    push @MODNAMES, $modname;

    $npath = "../$npath";

    link $mod, $l1 or warn "[e] link $mod, $l1\n";
    symlink $npath, $l2 or warn "[e] symlink $mod, $l2\n";

}
    print MODULES join "\n" => sort @MODULES;
    print MODNAME join "\n" => sort @MODNAMES;
