#!/bin/sh

## hyphop ##

. ./,config

[ "$out" ] || out=../logs/patched-rt.log

cd $src

for p in ../kernel-patches-rt/*.patch; do
echo $p

patch -p1 < $p || { 

	echo "[FAIL] $p" 
	exit 1
}

done

cd ..


