#!/bin/sh

## hyphop ##

. ./,config

for mod in $mod_out_links/*; do

    l=`readlink $mod`

    [ "${l#/}" = "$l" ] || {

    l2=${l#$PWD/$mod_rpath/}
    cmd="ln -sf ../modules/$l2 $mod"
    echo $cmd
    $cmd

    }
done

