#!/bin/sh

## hyphop ##

. ./,config

./kernel_dirs

echo "$kernel_path modules => $mod_path"

cmd="make -C $kernel_path $kernel_build_args modules_install \
    INSTALL_MOD_PATH=$mod_path"

eval $cmd "1>>$kernel_log_out" "2>>$kernel_err_out" || {
    echo "[e] check $kernel_err_out"
    tail $kernel_err_out
    exit 1
}

echo "[i] OK"

echo $cmd

rm -rf $mod_out
rm -rf $mod_out_links

[ -d $mod_out_links ] || mkdir $mod_out_links
[ -d $mod_out ] || mkdir $mod_out

