#!/bin/sh
## hyphop ##

## online command - easy make 

usage() { echo "USAGE:

    wget https://raw.githubusercontent.com/hyphop/miZy-linux-kernel/master/make_it_easy -O- | sh -

"
}

mkdir /tmp/zero_builder
cd /tmp/zero_builder

git clone https://github.com/hyphop/miZy-linux-kernel.git
cd miZy-linux-kernel

./kernel_prepare
./kernel_build_all
