#!/bin/sh

## hyphop ##

. ./,config

./kernel_dirs

#exit

[ -d $kernel_path ] || {

    echo "PREPARE SOURCE FIRST: 

    ./kernel_prepare
"
    exit 1
}

cmd="make -C $kernel_path $kernel_build_args"
echo $cmd
time $cmd $args
# 1>$logs/kernel.log 


ls -l1 $kernel_image
cmd="cp $kernel_image $kernel_out/Image"
echo $cmd
$cmd
