#!/bin/sh

## hyphop ##

## generate uboot mkimage 

usage() { echo "

USAGE $0

    mkimages /tmp Image gzip [../bin/uImage.gzip]

"
exit
}

wdir=$1
i=$2
c=$3

[ "$i" = "" ] && i="Image"
ii=$wdir/$i.$c

[ -f $ii ] || usage

size=`stat --printf %s $ii`

#sizeh=`printf %08x $size`

[ "$out" = "" ] && out="$wdir/u$i.$c"


## header 

tmp=/tmp

wd=`dirname $0`
pwd=$PWD
oi="$wd/u$i.$c.hdr"
ou="$tmp/u$i.$c"
oh="$ou.hdr"

[ "$4" = "" ] || ou=$4

echo "$0 for $ii =>
    $pwd/$ou, set $i size $size"

#echo "$oi => $oh"
cp $oi $oh

ddr12="dd seek=3 bs=4 count=1 conv=notrunc of=$oh"
ddr24="dd seek=6 bs=4 count=1 conv=notrunc of=$oh"
#ddr="hd"

# mizy uboot can accept wrong crc32
$wd/crc32 $ii N | $ddr24  2>/dev/null

#[ "" ] && {
which perl 1>/dev/null && {
    perl -e 'syswrite STDOUT, pack N => '$size | $ddr12 2>/dev/null
    echo "$ii => $ou"
    cat $oh $ii > $ou
#    which file 1>/dev/null && file $ou
    exit 0
}
#}

which xxd 1>/dev/null && {
    printf "0: %.8x" $size | xxd -r -g0 | $ddr12 2>/dev/null
    echo "$ii => $ou"
    cat $oh $ii > $ou
#    which file 1>/dev/null && file $ou
    exit 0
}


echo "[e] try install mkimage u-boot-tools" 1>&2

exit 1

#uImage.gzip.hdr

#a=$(echo -n $sizeh  | cut -c1,2)
#b=$(echo -n $sizeh  | cut -c3,4)
#c=$(echo -n $sizeh  | cut -c5,6)
#d=$(echo -n $sizeh  | cut -c7,8)

#echo $sizeh

#echo $a $b $c $d 1>&2
#
#echo -n x10

#echo ${sizeh:0:2}
#echo ${sizeh:2:2}
#echo ${sizeh:4:2}
#echo ${sizeh:6:2}

#eval sizeb="\\x${sizeh}"
#printf "$sizeh"

