#!/bin/sh

## hyphop ##

usage() { echo "

USAGE $0

    mkimages /tmp Image gzip [../bin/uImage.gzip]

"
exit
}

wdir=$1
i=$2
c=$3

[ "$i" = "" ] && i="Image"
ii=$wdir/$i.$c

size=`stat --printf %s $ii`

#sizeh=`printf %08x $size`

[ "$out" = "" ] && out="$wdir/u$i.$c"


## header 

tmp=/tmp

wd=`dirname $0`
pwd=$PWD
oi="$wd/u$i.$c.hdr"
ou="$tmp/u$i.$c"
oh="$ou.hdr"

[ "$4" = "" ] || ou=$4

echo "$0 for $ii =>
    $pwd/$ou, set $i size $size"

#echo "$oi => $oh"
cp $oi $oh


printf "0: %.8x" $size | xxd -r -g0 | dd seek=3 bs=4 count=1 conv=notrunc of=$oh 2>/dev/null

echo "$ii => $ou"
cat $oh $ii > $ou

#uImage.gzip.hdr

#a=$(echo -n $sizeh  | cut -c1,2)
#b=$(echo -n $sizeh  | cut -c3,4)
#c=$(echo -n $sizeh  | cut -c5,6)
#d=$(echo -n $sizeh  | cut -c7,8)

#echo $sizeh

#echo $a $b $c $d 1>&2
#
#echo -n x10

#echo ${sizeh:0:2}
#echo ${sizeh:2:2}
#echo ${sizeh:4:2}
#echo ${sizeh:6:2}

#eval sizeb="\\x${sizeh}"
#printf "$sizeh"

